# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPokemon', models.IntegerField(default=0)),
                ('nomPokemon', models.CharField(max_length=64)),
                ('generationPokemon', models.IntegerField(default=0)),
                ('coutPokemon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomType', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type1', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='relation',
            name='type2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type2', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='typePokemon',
            field=models.ManyToManyField(to='pokedex.Type'),
        ),
    ]
