# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pokemon', models.IntegerField(default=0)),
                ('nom_pokemon', models.CharField(max_length=64)),
                ('generation_pokemon', models.IntegerField(default=0)),
                ('cout_pokemon', models.IntegerField(default=0)),
                ('image_pokemon', models.FileField(default='006.png', upload_to='pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('pokemon_equipe', models.ManyToManyField(blank=True, to='pokedex.Pokemon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='type_defensif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_defensif', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='relation',
            name='type_offensif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_offensif', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type_pokemon',
            field=models.ManyToManyField(to='pokedex.Type'),
        ),
    ]
