# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPokemon', models.CharField(max_length=64)),
                ('type1', models.CharField(max_length=64)),
                ('type2', models.CharField(max_length=64)),
            ],
        ),
    ]
