# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='nomPokemon',
            new_name='nom_pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type2',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='cout_pokemon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='generation_pokemon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='numero_pokemon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relation',
            name='type_defensif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_defensif', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='relation',
            name='type_offensif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_offensif', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type_pokemon',
            field=models.ManyToManyField(to='pokedex.Type'),
        ),
    ]
