TYPE_CHOICES = (
	(-1,("Type")),
	(1,("Acier")),
	(2,("Combat")),
	(3,("Dragon")),
	(4,("Eau")),
	(5,("Electrik")),
	(6,("Fée")),
	(7,("Feu")),
	(8,("Glace")),
	(9,("Insecte")),
	(10,("Normal")),
	(11,("Plante")),
	(12,("Poison")),
	(13,("Psy")),
	(14,("Roche")),
	(15,("Sol")),
	(16,("Spectre")),
	(17,("Tenebres")),
	(18,("Vol")),
)

GEN_CHOICES = (
	(-1,("Generation")),
	(1,("Generation 1")),
	(2,("Generation 2")),
	(3,("Generation 3")),
	(4,("Generation 4")),
	(5,("Generation 5")),
	(6,("Generation 6")),
	(7,("Generation 7")),
)
